name: Deploy FastAPI to Azure Web App

on:
  push:
    branches:
      - production
      - staging
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set environment variables based on branch
        run: |
          if [[ $GITHUB_REF == 'refs/heads/production' ]]; then
            echo "AZURE_BACKEND_APP_NAME=${{ secrets.PROD_AZURE_BACKEND_APP_NAME }}" >> $GITHUB_ENV
            echo "AZURE_BACKEND_PUBLISH_PROFILE=${{ secrets.PROD_AZURE_BACKEND_PUBLISH_PROFILE }}" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == 'refs/heads/staging' ]]; then
            echo "AZURE_BACKEND_APP_NAME=${{ secrets.STAGING_AZURE_BACKEND_APP_NAME }}" >> $GITHUB_ENV
            echo "AZURE_BACKEND_PUBLISH_PROFILE=${{ secrets.STAGING_AZURE_BACKEND_PUBLISH_PROFILE }}" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == 'refs/heads/development' ]]; then
            echo "AZURE_BACKEND_APP_NAME=${{ secrets.DEV_AZURE_BACKEND_APP_NAME }}" >> $GITHUB_ENV
            echo "AZURE_BACKEND_PUBLISH_PROFILE=${{ secrets.DEV_AZURE_BACKEND_PUBLISH_PROFILE }}" >> $GITHUB_ENV
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd api
          pip install -r requirements.txt

      - name: Prepare deployment artifacts
        run: |
          cd api
          mkdir -p deploy
          cp -r . ./deploy
          zip -r release.zip deploy

      - name: Upload deployment artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fastapi-app
          path: api/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download deployment artifacts
        uses: actions/download-artifact@v4
        with:
          name: fastapi-app

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure Web App Name for Frontend and Backend
        id: set-app-names
        run: |
          if [[ $GITHUB_REF == 'refs/heads/production' ]]; then
            echo "AZURE_FRONTEND_APP_NAME=${{ secrets.PROD_AZURE_FRONTEND_APP_NAME }}" >> $GITHUB_ENV
            echo "AZURE_BACKEND_APP_NAME=${{ secrets.PROD_AZURE_BACKEND_APP_NAME }}" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == 'refs/heads/staging' ]]; then
            echo "AZURE_FRONTEND_APP_NAME=${{ secrets.STAGING_AZURE_FRONTEND_APP_NAME }}" >> $GITHUB_ENV
            echo "AZURE_BACKEND_APP_NAME=${{ secrets.STAGING_AZURE_BACKEND_APP_NAME }}" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == 'refs/heads/development' ]]; then
            echo "AZURE_FRONTEND_APP_NAME=${{ secrets.DEV_AZURE_FRONTEND_APP_NAME }}" >> $GITHUB_ENV
            echo "AZURE_BACKEND_APP_NAME=${{ secrets.DEV_AZURE_BACKEND_APP_NAME }}" >> $GITHUB_ENV
          fi
  
      - name: Deploy FastAPI to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_BACKEND_APP_NAME }}
          slot-name: 'Production'
          package: api/release.zip
          publish-profile: ${{ env.AZURE_BACKEND_PUBLISH_PROFILE }}
