name: Build and deploy Next.js or FastAPI app to Azure Web App

on:
  push:
    branches:
      - production  # 本番環境
      - staging     # 検証環境
      - development # 開発環境
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Determine environment
        id: env-setup
        run: |
          if [[ $GITHUB_REF == 'refs/heads/production' ]]; then
            echo "env=production" >> $GITHUB_ENV
            echo "NEXT_PUBLIC_URL=${{ secrets.PROD_NEXT_PUBLIC_URL }}" >> $GITHUB_ENV
            echo "AZURE_APP_NAME=${{ secrets.PROD_AZURE_FRONTEND_APP_NAME }}" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == 'refs/heads/staging' ]]; then
            echo "env=staging" >> $GITHUB_ENV
            echo "NEXT_PUBLIC_URL=${{ secrets.STAGING_NEXT_PUBLIC_URL }}" >> $GITHUB_ENV
            echo "AZURE_APP_NAME=${{ secrets.STAGING_AZURE_FRONTEND_APP_NAME }}" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == 'refs/heads/development' ]]; then
            echo "env=development" >> $GITHUB_ENV
            echo "NEXT_PUBLIC_URL=${{ secrets.DEV_NEXT_PUBLIC_URL }}" >> $GITHUB_ENV
            echo "AZURE_APP_NAME=${{ secrets.DEV_AZURE_FRONTEND_APP_NAME }}" >> $GITHUB_ENV
          fi
          echo "NEXT_PUBLIC_AUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build
        env:
          NEXT_PUBLIC_URL: ${{ env.NEXT_PUBLIC_URL }}
          NEXT_PUBLIC_AUTH_SECRET: ${{ env.NEXT_PUBLIC_AUTH_SECRET }}

      - name: Prepare deployment artifacts
        run: |
          mkdir -p deploy
          cp -r ./.next/standalone/. ./deploy
          cp -r ./public ./deploy
          cp -r ./.next/static ./deploy/.next/static
          cp ./package.json ./deploy
          cp ./package-lock.json ./deploy

      - name: Zip deployment artifacts
        run: zip -r release.zip deploy

      - name: Upload deployment artifacts
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download deployment artifacts
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip deployment artifacts
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_APP_NAME }}  # 本番・検証・開発環境に対応するApp Serviceの名前
          slot-name: 'Production'
          package: deploy
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
